services:
  # postgresdb:  # Uncomment to connect a Postgres DB
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: secret
  wallet-api:
    image: waltid/wallet-api:latest
    build:
      context: ../
      dockerfile: waltid-wallet-api/Dockerfile
    links:
      - db
    volumes:
      - ./wallet-api/config:/waltid-wallet-api/config
      - ./wallet-api/walt.yaml:/waltid-wallet-api/walt.yaml
      - ./wallet-api/data:/waltid-wallet-api/data

  issuer-api:
    platform: linux/x86_64
    image: waltid/issuer-api:latest
    volumes:
      - ./issuer-api/config:/waltid-issuer-api/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  verifier-api:
    platform: linux/x86_64
    image: waltid/verifier-api:latest
    volumes:
      - ./verifier-api/config:/waltid-verifier-api/config

  waltid-web-wallet:
    image: waltid/waltid-web-wallet:latest
    environment:
      NUXT_PUBLIC_ISSUER_CALLBACK_URL: "http://localhost:$WALLET_FRONTEND_PORT"
      PORT: $WALLET_FRONTEND_PORT

  web-portal:
    platform: linux/x86_64
    image: waltid/portal:latest
    environment:
      NEXT_PUBLIC_VC_REPO: "http://localhost:$VC_REPO_PORT"
      NEXT_PUBLIC_ISSUER: "http://localhost:$ISSUER_API_PORT"
      NEXT_PUBLIC_VERIFIER: "http://localhost:$VERIFIER_API_PORT"
      NEXT_PUBLIC_WALLET: "http://localhost:$WALLET_FRONTEND_PORT"
      PORT: $WEB_PORTAL_PORT

  vc-repo:
    platform: linux/x86_64
    image: waltid/vc-repository:latest
    environment:
      PORT: $VC_REPO_PORT
  db:
    image: postgres:alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - wallet-api-db:/waltid-wallet-api/data/postgresql
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    ports:
      - '5432:5432'
  phpmyadmin:
    image: dpage/pgadmin4
    links:
      - db
    env_file:
      - ./pgadmin.env
    volumes:
      - pgadmin:/waltid-wallet-api/data/pgadmin
    restart: always
    ports:
      - 8081:80

  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:

      - target: "$WALLET_BACKEND_PORT"
        published: $WALLET_BACKEND_PORT # wallet-api
        protocol: tcp
        mode: host

      - target: "$ISSUER_API_PORT"
        published: $ISSUER_API_PORT # issuer-api
        protocol: tcp
        mode: host

      - target: "$VERIFIER_API_PORT"
        published: $VERIFIER_API_PORT # verifier-api
        protocol: tcp
        mode: host

      - target: "$WALLET_FRONTEND_PORT"
        published: $WALLET_FRONTEND_PORT # waltid-web-wallet
        protocol: tcp
        mode: host

      - target: "$WEB_PORTAL_PORT"
        published: $WEB_PORTAL_PORT # web-portal
        protocol: tcp
        mode: host

      - target: "$VC_REPO_PORT"
        published: $VC_REPO_PORT # vc-repo
        protocol: tcp
        mode: host

      - target: "$PG_ADMIN_PORT"
        published: "80" # pg-admin
        protocol: tcp
        mode: host

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
volumes:
    wallet-api-db:
    pgadmin:

