name: issuer-api-test

on:
  push:
    branches: [ main ]  # You can adjust the branches to trigger on

jobs:
  test_api:
    runs-on: ubuntu-latest  # Adjust runner OS if needed

    services:
      issuer-api:
        image: waltid/issuer-api:latest  # Specify image and tag
        volumes:
          - ./issuer-api/config:/waltid-issuer-api/config:ro  # Mount config volume read-only
        ports:
          - 7002:7002  # Map container port to host port

    steps:
      - uses: actions/checkout@v3

      - name: Verify issuer-api connection (using curl and monitor logs)
        run: |
          docker logs -f issuer-api &  # Run logs in background
          until curl -sSf http://localhost:7002/health; do
            echo "Waiting for issuer-api service to be ready..."
            sleep 5
          done
          echo "issuer-api service is healthy."
          wait  # Wait for logs process to finish

      # Option 1: Display logs at the end (uncommented)
      - name: Display issuer-api container logs (Option 1)
        run: |
          docker logs issuer-api

      - name: Run your issuer-api tests (replace with your actual tests)
        run: |
          # Replace with your specific test commands
          echo "Running issuer-api tests..."
          # Your test commands go here (e.g., pytest, unit tests, etc.)
