name: issuer-api test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      issuer-api:
        image: waltid/issuer-api:latest
        ports:
          - 7002
    steps:
      - name: Wait for service to start
        run: sleep 10s
      - name: Verify issuer-api connection from host
        run: |
          echo "${{ toJson(job) }}"
          curl -s http://localhost:7002/health || exit 1
          docker logs "${{ job.services.issuer-api.id }}"
