
name: issuer-api test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      issuer-api:
        image: waltid/issuer-api:latest
        volumes:
          - ./issuer-api/config:/waltid-issuer-api/config
        ports:
          - 7002

    steps:
      - uses: actions/checkout@v3
        with: 
         paths: "!issuer-api/config" 

      - name: Wait for issuer-api service to be ready
        run: |
          echo "Waiting for issuer-api service to be ready"
          status="starting"
          while [ "$status" != "healthy" ]; do
            status=$(curl -s http://localhost:7002/health/ || true)  # Attempt health check via curl
            echo "issuer-api service is $status."
            if [ "$status" != "healthy" ]; then
              sleep 5
            fi
          done

      - name: Verify issuer-api connection from host
        run: |
          echo "Waiting for issuer-api service to be ready"
          status="starting"
          while [ "$status" != "healthy" ]; do
            status=$(/usr/bin/docker inspect --format="{{if .State.Health}}{{print .State.Health.Status}}{{end}}" "${{ job.services.issuer-api.id }}")
            echo "issuer-api service is $status."
            if [ "$status" != "healthy" ]; then
              sleep 5
            fi
          done
