name: Pre-release on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Pre-release"
    runs-on: ubuntu-latest 
    steps:
      - name: Pull image
        run: docker compose pull 
      - name: Start container
        run: docker compose up issuer-api
      - name: Wait for container
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: issuer-api
          wait-time: 300
          require-status: running
          require-healthy: true
