name: Docker Compose Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  WALLET_BACKEND_PORT: 7001
  ISSUER_API_PORT: 7002
  VERIFIER_API_PORT: 7003

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.8
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start container
        run: docker run -d --rm --name issuer-api waltid/issuer-api
      - name: Wait for container
        uses: docker/build-push-action@v5
        with:
          container: issuer-api
          wait-time: 50
          require-status: running
          require-healthy: true
