name: Run Docker Compose Tests

on:
  push:
    branches: [ main ]  

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
   
      - uses: actions/checkout@v3
      - uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose/docker-compose.yaml"
          services: |
            issuer-api
            verifier-api
            wallet-api
            
