name: Test Docker Compose up

on:
  push: # Trigger on push event
    branches: [ main ] # Only for pushes to main branch
  workflow_dispatch: # Allow manual workflow run
  schedule: # Scheduled execution
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  test: # Job name
    runs-on: ubuntu-latest # Job runs on ubuntu-latest runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: docker-compose --version # Check Docker Compose version

      - name: Setup Docker Compose 
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # Specify Docker Compose version (if needed)

      - name: Start Docker containers
        run: docker-compose -f ./docker-compose/docker-compose.yaml up -d
        working-directory: ${{ github.workspace }}

      - name: Check running containers
        run: docker ps -a
      - name: echo wallet-api
        run: docker-compose exec wallet-api echo "wallet-api is up"
      
          
