name: Docker Compose Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.12-dind
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Compose
      uses: docker/compose-action@v2
      with:
        file: ./docker-compose/docker-compose.yaml
    - name: Run Docker Compose
      run: docker-compose -f ./docker-compose/docker-compose.yaml up -d
