
name: Docker 
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


       
      - run: docker-compose --version
      
      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' 

      - name: Start Docker Compose services
        run:  docker-compose -f ./docker-compose/docker-compose.yaml up -d

      - name: Wait for services to start
        run: ./docker-compose/check_service.sh ./docker-compose/docker-compose.yaml

      - name: Start everything
        uses: myorg/our-compose-infrastructure-project@v4
        with:
          wait-before-exiting: 180 # Max amount of time to wait for containers uptime before considering it a failure
