name: Measure performance
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 2 * * 1-5'

jobs:
  measure:
    runs-on: [ self-hosted, 4xlarge-on-demand, dedicated-storage ]
    steps:
      - uses: actions/checkout@v4

      - name: Start Docker Compose services
        run:  docker-compose -f ./docker-compose/docker-compose.yaml up -d

      - name: Wait for services to start
        run: ./docker-compose/check_service.sh ./docker-compose/docker-compose.yaml

      - name: Start everything
        uses: myorg/our-compose-infrastructure-project@v4
        with:
          wait-before-exiting: 180 # Max amount of time to wait for containers uptime before considering it a failure
